# Raw Kubernetes DaemonSet manifest for users without Helm.
# For production use, prefer the Helm chart in charts/kubepulse/.

apiVersion: v1
kind: Namespace
metadata:
  name: kubepulse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubepulse
  namespace: kubepulse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubepulse
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubepulse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubepulse
subjects:
  - kind: ServiceAccount
    name: kubepulse
    namespace: kubepulse
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubepulse
  namespace: kubepulse
  labels:
    app: kubepulse
spec:
  selector:
    matchLabels:
      app: kubepulse
  template:
    metadata:
      labels:
        app: kubepulse
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      hostPID: true
      serviceAccountName: kubepulse
      containers:
        - name: kubepulse
          image: kubepulse:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
                - SYS_PTRACE
                - BPF
          env:
            - name: KUBEPULSE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBEPULSE_METRICS_ADDR
              value: ":9090"
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: sys-bpf
              mountPath: /sys/fs/bpf
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys-bpf
          hostPath:
            path: /sys/fs/bpf
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
      tolerations:
        - operator: Exists
