// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDnsTracer returns the embedded CollectionSpec for dnsTracer.
func loadDnsTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dnsTracer: %w", err)
	}

	return spec, err
}

// loadDnsTracerObjects loads dnsTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dnsTracerObjects
//	*dnsTracerPrograms
//	*dnsTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDnsTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDnsTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dnsTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsTracerSpecs struct {
	dnsTracerProgramSpecs
	dnsTracerMapSpecs
	dnsTracerVariableSpecs
}

// dnsTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsTracerProgramSpecs struct {
	KprobeUdpSendmsg *ebpf.ProgramSpec `ebpf:"kprobe_udp_sendmsg"`
}

// dnsTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsTracerMapSpecs struct {
	DnsEvents *ebpf.MapSpec `ebpf:"dns_events"`
}

// dnsTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsTracerVariableSpecs struct {
}

// dnsTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDnsTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsTracerObjects struct {
	dnsTracerPrograms
	dnsTracerMaps
	dnsTracerVariables
}

func (o *dnsTracerObjects) Close() error {
	return _DnsTracerClose(
		&o.dnsTracerPrograms,
		&o.dnsTracerMaps,
	)
}

// dnsTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDnsTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsTracerMaps struct {
	DnsEvents *ebpf.Map `ebpf:"dns_events"`
}

func (m *dnsTracerMaps) Close() error {
	return _DnsTracerClose(
		m.DnsEvents,
	)
}

// dnsTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDnsTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsTracerVariables struct {
}

// dnsTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDnsTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsTracerPrograms struct {
	KprobeUdpSendmsg *ebpf.Program `ebpf:"kprobe_udp_sendmsg"`
}

func (p *dnsTracerPrograms) Close() error {
	return _DnsTracerClose(
		p.KprobeUdpSendmsg,
	)
}

func _DnsTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnstracer_x86_bpfel.o
var _DnsTracerBytes []byte
