// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDropTracer returns the embedded CollectionSpec for dropTracer.
func loadDropTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DropTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dropTracer: %w", err)
	}

	return spec, err
}

// loadDropTracerObjects loads dropTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dropTracerObjects
//	*dropTracerPrograms
//	*dropTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDropTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDropTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dropTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dropTracerSpecs struct {
	dropTracerProgramSpecs
	dropTracerMapSpecs
	dropTracerVariableSpecs
}

// dropTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dropTracerProgramSpecs struct {
	TracepointKfreeSkb *ebpf.ProgramSpec `ebpf:"tracepoint_kfree_skb"`
}

// dropTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dropTracerMapSpecs struct {
	DropEvents *ebpf.MapSpec `ebpf:"drop_events"`
}

// dropTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dropTracerVariableSpecs struct {
}

// dropTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDropTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type dropTracerObjects struct {
	dropTracerPrograms
	dropTracerMaps
	dropTracerVariables
}

func (o *dropTracerObjects) Close() error {
	return _DropTracerClose(
		&o.dropTracerPrograms,
		&o.dropTracerMaps,
	)
}

// dropTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDropTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type dropTracerMaps struct {
	DropEvents *ebpf.Map `ebpf:"drop_events"`
}

func (m *dropTracerMaps) Close() error {
	return _DropTracerClose(
		m.DropEvents,
	)
}

// dropTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDropTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type dropTracerVariables struct {
}

// dropTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDropTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type dropTracerPrograms struct {
	TracepointKfreeSkb *ebpf.Program `ebpf:"tracepoint_kfree_skb"`
}

func (p *dropTracerPrograms) Close() error {
	return _DropTracerClose(
		p.TracepointKfreeSkb,
	)
}

func _DropTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed droptracer_x86_bpfel.o
var _DropTracerBytes []byte
