// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadExecTracer returns the embedded CollectionSpec for execTracer.
func loadExecTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execTracer: %w", err)
	}

	return spec, err
}

// loadExecTracerObjects loads execTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execTracerObjects
//	*execTracerPrograms
//	*execTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execTracerSpecs struct {
	execTracerProgramSpecs
	execTracerMapSpecs
	execTracerVariableSpecs
}

// execTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execTracerProgramSpecs struct {
	TracepointSchedProcessExec *ebpf.ProgramSpec `ebpf:"tracepoint_sched_process_exec"`
}

// execTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execTracerMapSpecs struct {
	ExecEvents *ebpf.MapSpec `ebpf:"exec_events"`
}

// execTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execTracerVariableSpecs struct {
}

// execTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type execTracerObjects struct {
	execTracerPrograms
	execTracerMaps
	execTracerVariables
}

func (o *execTracerObjects) Close() error {
	return _ExecTracerClose(
		&o.execTracerPrograms,
		&o.execTracerMaps,
	)
}

// execTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type execTracerMaps struct {
	ExecEvents *ebpf.Map `ebpf:"exec_events"`
}

func (m *execTracerMaps) Close() error {
	return _ExecTracerClose(
		m.ExecEvents,
	)
}

// execTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type execTracerVariables struct {
}

// execTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type execTracerPrograms struct {
	TracepointSchedProcessExec *ebpf.Program `ebpf:"tracepoint_sched_process_exec"`
}

func (p *execTracerPrograms) Close() error {
	return _ExecTracerClose(
		p.TracepointSchedProcessExec,
	)
}

func _ExecTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed exectracer_x86_bpfel.o
var _ExecTracerBytes []byte
