// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type fileioTracerIoKey struct {
	_   structs.HostLayout
	Pid uint32
	Tid uint32
}

type fileioTracerIoVal struct {
	_       structs.HostLayout
	StartNs uint64
	Op      uint8
	Pad     [7]uint8
}

// loadFileioTracer returns the embedded CollectionSpec for fileioTracer.
func loadFileioTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileioTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load fileioTracer: %w", err)
	}

	return spec, err
}

// loadFileioTracerObjects loads fileioTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fileioTracerObjects
//	*fileioTracerPrograms
//	*fileioTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFileioTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFileioTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fileioTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileioTracerSpecs struct {
	fileioTracerProgramSpecs
	fileioTracerMapSpecs
	fileioTracerVariableSpecs
}

// fileioTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileioTracerProgramSpecs struct {
	KprobeVfsRead     *ebpf.ProgramSpec `ebpf:"kprobe_vfs_read"`
	KprobeVfsWrite    *ebpf.ProgramSpec `ebpf:"kprobe_vfs_write"`
	KretprobeVfsRead  *ebpf.ProgramSpec `ebpf:"kretprobe_vfs_read"`
	KretprobeVfsWrite *ebpf.ProgramSpec `ebpf:"kretprobe_vfs_write"`
}

// fileioTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileioTracerMapSpecs struct {
	FileioEvents *ebpf.MapSpec `ebpf:"fileio_events"`
	IoStart      *ebpf.MapSpec `ebpf:"io_start"`
}

// fileioTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileioTracerVariableSpecs struct {
}

// fileioTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFileioTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileioTracerObjects struct {
	fileioTracerPrograms
	fileioTracerMaps
	fileioTracerVariables
}

func (o *fileioTracerObjects) Close() error {
	return _FileioTracerClose(
		&o.fileioTracerPrograms,
		&o.fileioTracerMaps,
	)
}

// fileioTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFileioTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileioTracerMaps struct {
	FileioEvents *ebpf.Map `ebpf:"fileio_events"`
	IoStart      *ebpf.Map `ebpf:"io_start"`
}

func (m *fileioTracerMaps) Close() error {
	return _FileioTracerClose(
		m.FileioEvents,
		m.IoStart,
	)
}

// fileioTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFileioTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileioTracerVariables struct {
}

// fileioTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFileioTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileioTracerPrograms struct {
	KprobeVfsRead     *ebpf.Program `ebpf:"kprobe_vfs_read"`
	KprobeVfsWrite    *ebpf.Program `ebpf:"kprobe_vfs_write"`
	KretprobeVfsRead  *ebpf.Program `ebpf:"kretprobe_vfs_read"`
	KretprobeVfsWrite *ebpf.Program `ebpf:"kretprobe_vfs_write"`
}

func (p *fileioTracerPrograms) Close() error {
	return _FileioTracerClose(
		p.KprobeVfsRead,
		p.KprobeVfsWrite,
		p.KretprobeVfsRead,
		p.KretprobeVfsWrite,
	)
}

func _FileioTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed fileiotracer_x86_bpfel.o
var _FileioTracerBytes []byte
