// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadOomTracer returns the embedded CollectionSpec for oomTracer.
func loadOomTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OomTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load oomTracer: %w", err)
	}

	return spec, err
}

// loadOomTracerObjects loads oomTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*oomTracerObjects
//	*oomTracerPrograms
//	*oomTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOomTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOomTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// oomTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomTracerSpecs struct {
	oomTracerProgramSpecs
	oomTracerMapSpecs
	oomTracerVariableSpecs
}

// oomTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomTracerProgramSpecs struct {
	TracepointOomMarkVictim *ebpf.ProgramSpec `ebpf:"tracepoint_oom_mark_victim"`
}

// oomTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomTracerMapSpecs struct {
	OomEvents *ebpf.MapSpec `ebpf:"oom_events"`
}

// oomTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type oomTracerVariableSpecs struct {
}

// oomTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOomTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomTracerObjects struct {
	oomTracerPrograms
	oomTracerMaps
	oomTracerVariables
}

func (o *oomTracerObjects) Close() error {
	return _OomTracerClose(
		&o.oomTracerPrograms,
		&o.oomTracerMaps,
	)
}

// oomTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOomTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomTracerMaps struct {
	OomEvents *ebpf.Map `ebpf:"oom_events"`
}

func (m *oomTracerMaps) Close() error {
	return _OomTracerClose(
		m.OomEvents,
	)
}

// oomTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOomTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomTracerVariables struct {
}

// oomTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOomTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type oomTracerPrograms struct {
	TracepointOomMarkVictim *ebpf.Program `ebpf:"tracepoint_oom_mark_victim"`
}

func (p *oomTracerPrograms) Close() error {
	return _OomTracerClose(
		p.TracepointOomMarkVictim,
	)
}

func _OomTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed oomtracer_x86_bpfel.o
var _OomTracerBytes []byte
