// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadRetransmitTracer returns the embedded CollectionSpec for retransmitTracer.
func loadRetransmitTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RetransmitTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load retransmitTracer: %w", err)
	}

	return spec, err
}

// loadRetransmitTracerObjects loads retransmitTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*retransmitTracerObjects
//	*retransmitTracerPrograms
//	*retransmitTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRetransmitTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRetransmitTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// retransmitTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type retransmitTracerSpecs struct {
	retransmitTracerProgramSpecs
	retransmitTracerMapSpecs
	retransmitTracerVariableSpecs
}

// retransmitTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type retransmitTracerProgramSpecs struct {
	TracepointTcpRetransmit *ebpf.ProgramSpec `ebpf:"tracepoint_tcp_retransmit"`
}

// retransmitTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type retransmitTracerMapSpecs struct {
	RetransmitEvents *ebpf.MapSpec `ebpf:"retransmit_events"`
}

// retransmitTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type retransmitTracerVariableSpecs struct {
}

// retransmitTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRetransmitTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type retransmitTracerObjects struct {
	retransmitTracerPrograms
	retransmitTracerMaps
	retransmitTracerVariables
}

func (o *retransmitTracerObjects) Close() error {
	return _RetransmitTracerClose(
		&o.retransmitTracerPrograms,
		&o.retransmitTracerMaps,
	)
}

// retransmitTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRetransmitTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type retransmitTracerMaps struct {
	RetransmitEvents *ebpf.Map `ebpf:"retransmit_events"`
}

func (m *retransmitTracerMaps) Close() error {
	return _RetransmitTracerClose(
		m.RetransmitEvents,
	)
}

// retransmitTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRetransmitTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type retransmitTracerVariables struct {
}

// retransmitTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRetransmitTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type retransmitTracerPrograms struct {
	TracepointTcpRetransmit *ebpf.Program `ebpf:"tracepoint_tcp_retransmit"`
}

func (p *retransmitTracerPrograms) Close() error {
	return _RetransmitTracerClose(
		p.TracepointTcpRetransmit,
	)
}

func _RetransmitTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed retransmittracer_x86_bpfel.o
var _RetransmitTracerBytes []byte
