// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadRstTracer returns the embedded CollectionSpec for rstTracer.
func loadRstTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RstTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rstTracer: %w", err)
	}

	return spec, err
}

// loadRstTracerObjects loads rstTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rstTracerObjects
//	*rstTracerPrograms
//	*rstTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRstTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRstTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rstTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rstTracerSpecs struct {
	rstTracerProgramSpecs
	rstTracerMapSpecs
	rstTracerVariableSpecs
}

// rstTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rstTracerProgramSpecs struct {
	TracepointTcpSendReset *ebpf.ProgramSpec `ebpf:"tracepoint_tcp_send_reset"`
}

// rstTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rstTracerMapSpecs struct {
	RstEvents *ebpf.MapSpec `ebpf:"rst_events"`
}

// rstTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rstTracerVariableSpecs struct {
}

// rstTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRstTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type rstTracerObjects struct {
	rstTracerPrograms
	rstTracerMaps
	rstTracerVariables
}

func (o *rstTracerObjects) Close() error {
	return _RstTracerClose(
		&o.rstTracerPrograms,
		&o.rstTracerMaps,
	)
}

// rstTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRstTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type rstTracerMaps struct {
	RstEvents *ebpf.Map `ebpf:"rst_events"`
}

func (m *rstTracerMaps) Close() error {
	return _RstTracerClose(
		m.RstEvents,
	)
}

// rstTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRstTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type rstTracerVariables struct {
}

// rstTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRstTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type rstTracerPrograms struct {
	TracepointTcpSendReset *ebpf.Program `ebpf:"tracepoint_tcp_send_reset"`
}

func (p *rstTracerPrograms) Close() error {
	return _RstTracerClose(
		p.TracepointTcpSendReset,
	)
}

func _RstTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rsttracer_x86_bpfel.o
var _RstTracerBytes []byte
