// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpTracerConnKey struct {
	_       structs.HostLayout
	Pid     uint32
	_       [4]byte
	SockPtr uint64
}

type tcpTracerConnVal struct {
	_       structs.HostLayout
	StartNs uint64
	Saddr   uint32
	Daddr   uint32
	Sport   uint16
	Dport   uint16
	Uid     uint32
}

// loadTcpTracer returns the embedded CollectionSpec for tcpTracer.
func loadTcpTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpTracer: %w", err)
	}

	return spec, err
}

// loadTcpTracerObjects loads tcpTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpTracerObjects
//	*tcpTracerPrograms
//	*tcpTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpTracerSpecs struct {
	tcpTracerProgramSpecs
	tcpTracerMapSpecs
	tcpTracerVariableSpecs
}

// tcpTracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpTracerProgramSpecs struct {
	KprobeTcpClose   *ebpf.ProgramSpec `ebpf:"kprobe_tcp_close"`
	KprobeTcpConnect *ebpf.ProgramSpec `ebpf:"kprobe_tcp_connect"`
}

// tcpTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpTracerMapSpecs struct {
	ConnStart *ebpf.MapSpec `ebpf:"conn_start"`
	TcpEvents *ebpf.MapSpec `ebpf:"tcp_events"`
}

// tcpTracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpTracerVariableSpecs struct {
}

// tcpTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpTracerObjects struct {
	tcpTracerPrograms
	tcpTracerMaps
	tcpTracerVariables
}

func (o *tcpTracerObjects) Close() error {
	return _TcpTracerClose(
		&o.tcpTracerPrograms,
		&o.tcpTracerMaps,
	)
}

// tcpTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpTracerMaps struct {
	ConnStart *ebpf.Map `ebpf:"conn_start"`
	TcpEvents *ebpf.Map `ebpf:"tcp_events"`
}

func (m *tcpTracerMaps) Close() error {
	return _TcpTracerClose(
		m.ConnStart,
		m.TcpEvents,
	)
}

// tcpTracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpTracerVariables struct {
}

// tcpTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpTracerPrograms struct {
	KprobeTcpClose   *ebpf.Program `ebpf:"kprobe_tcp_close"`
	KprobeTcpConnect *ebpf.Program `ebpf:"kprobe_tcp_connect"`
}

func (p *tcpTracerPrograms) Close() error {
	return _TcpTracerClose(
		p.KprobeTcpClose,
		p.KprobeTcpConnect,
	)
}

func _TcpTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcptracer_x86_bpfel.o
var _TcpTracerBytes []byte
