// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package fileio

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfIoKey struct {
	_   structs.HostLayout
	Pid uint32
	Tid uint32
}

type bpfIoVal struct {
	_       structs.HostLayout
	StartNs uint64
	Op      uint8
	Pad     [7]uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeVfsRead     *ebpf.ProgramSpec `ebpf:"kprobe_vfs_read"`
	KprobeVfsWrite    *ebpf.ProgramSpec `ebpf:"kprobe_vfs_write"`
	KretprobeVfsRead  *ebpf.ProgramSpec `ebpf:"kretprobe_vfs_read"`
	KretprobeVfsWrite *ebpf.ProgramSpec `ebpf:"kretprobe_vfs_write"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	FileioEvents *ebpf.MapSpec `ebpf:"fileio_events"`
	IoStart      *ebpf.MapSpec `ebpf:"io_start"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	FileioEvents *ebpf.Map `ebpf:"fileio_events"`
	IoStart      *ebpf.Map `ebpf:"io_start"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.FileioEvents,
		m.IoStart,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeVfsRead     *ebpf.Program `ebpf:"kprobe_vfs_read"`
	KprobeVfsWrite    *ebpf.Program `ebpf:"kprobe_vfs_write"`
	KretprobeVfsRead  *ebpf.Program `ebpf:"kretprobe_vfs_read"`
	KretprobeVfsWrite *ebpf.Program `ebpf:"kretprobe_vfs_write"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeVfsRead,
		p.KprobeVfsWrite,
		p.KretprobeVfsRead,
		p.KretprobeVfsWrite,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
